server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        ## USER SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        ## FUND TRANSFER SERVICE
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**



eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


